checks:
  javascript: true

build:
  environment:
    node: v15.8.0
  nodes:
    analysis:
      project_setup:
        override: true
    coverage:
      environment:
        docker: true
      tests:
        before:
          - 'yarn global add typescript coveralls codacy-coverage npm-run-all wait-on'
          - 'docker pull arnaudf93/dashwebservices:latest'
          - 'docker run -d -p 8080:8080 --name dash-webservices  arnaudf93/dashwebservices'
        override:
          - js-scrutinizer-run
          - command: 'yarn run ci'
            coverage:
              file: ./coverage/clover.xml
              format: clover

filter:
  excluded_paths:
    - 'src/tests/'
    # Everything in a root level "tests" directory will be excluded
  dependency_paths:
    - 'lib/'
    # Everything in a root level "lib" directory will be excluded from analysis
    # but treated as a dependency
