checks:
  javascript: true

build:
  environment:
    node: v15.8.0
  nodes:
    analysis:
      project_setup:
        override: true
    coverage:
      environment:
        docker: true
      tests:
        before:
          - 'yarn global add typescript coveralls codacy-coverage npm-run-all wait-on'
          - 'docker pull arnaudf93/dashwebservices:latest'
          - 'docker run -d -p 8080:8080 --name dash-webservices  arnaudf93/dashwebservices'
        override:
          - js-scrutinizer-run
          - 'yarn run ci'
          - mkdir coverage-reports || true && mkdir .nyc_output || true
          - cp cypress-coverage/coverage-final.json coverage-reports/from-cypress.json
          - cp jest-coverage/coverage-final.json coverage-reports/from-jest.json
          - npx nyc merge coverage-reports && mv coverage.json .nyc_output/out.json
          - npx nyc report --reporter lcov --report-dir coverage
          - coverage:
              file: ./coverage/lcov.info
              format: lcov
filter:
  excluded_paths:
    - 'src/tests/'
    # Everything in a root level "tests" directory will be excluded
  dependency_paths:
    - 'lib/'
    # Everything in a root level "lib" directory will be excluded from analysis
    # but treated as a dependency
