checks:
    javascript: true

build:
  environment:
    node: v10.13.0
  nodes:
    analysis:
      project_setup:
        override: true
    coverage:
      tests:
        override:
           - js-scrutinizer-run
           - command : 'npm test -- --coverage'
             coverage:
              file: ./coverage/lcov.info
              format: lcov
                  
filter:
    excluded_paths:
        - "src/tests/"
        # Everything in a root level "tests" directory will be excluded
    dependency_paths:
        - "lib/"
        # Everything in a root level "lib" directory will be excluded from analysis
        # but treated as a dependency