language: node_js

node_js:
  - node
  - 9
  - 8

env:
  - NODE_ENV=travis

before_install:
  - npm install -g coveralls codacy-coverage

script: npm test -- --coverage

after_success:
  - cat ./coverage/clover.xml | coveralls
  - cat ./coverage/clover.xml | codacy-coverage