language: node_js

node_js:
  - node
  - 12
  - 11

services:
  - docker

install: npm ci

cache:
  directories:
  - "$HOME/.npm"

env:
  - NODE_ENV=travis

before_install:
  - npm install -g typescript coveralls codacy-coverage
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker pull arnaudf93/dashwebservices:latest
  - docker run -p 8080:8080  arnaudf93/dashwebservices

script: npm test -- --coverage && cy:run

after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage
  - bash <(curl -s https://codecov.io/bash) 