language: node_js

node_js:
  - 15.8.0

services:
  - docker

install: yarn install --frozen-lockfile

cache:
  directories:
  - "$HOME/.npm"
  - ~/.cache

env:
  - NODE_ENV=travis

before_install:
  - yarn global add typescript coveralls codacy-coverage npm-run-all wait-on
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker pull arnaudf93/dashwebservices:latest
  - docker run -d -p 8080:8080  arnaudf93/dashwebservices

script: yarn install --frozen-lockfile

after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage
  - bash <(curl -s https://codecov.io/bash) 
