language: node_js

node_js:
  - node
  - 9
  - 8

env:
  - NODE_ENV=travis

before_install:
  - npm install -g coveralls codacy-coverage


after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage