version: '3'

services:
  backend:
    image: arnaudf93/dashwebservices:latest
    expose:
      - '8080'

  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5433
