version: '3'

services:
  database:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  backend:
    image: arnaudf93/dashwebservices:latest
    environment:
      - POSTGRES_URL=jdbc:postgresql://database:5432/dash_test
    links:
      - database
    ports:
      - 8080:8080
