# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 15.8.0 # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - run: yarn install --frozen-lockfile
    - run: npm i -g codacy-coverage npm-run-all wait-on
    - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: docker-compose up -d

    - run: npm run lint:styles
    - run: npm run eslint
    - run: npm run build

    - run: npm run ci

    - run :  mkdir coverage-reports || true && mkdir .nyc_output || true
    - run :  cp cypress-coverage/coverage-final.json coverage-reports/from-cypress.json
    - run :  cp jest-coverage/coverage-final.json coverage-reports/from-jest.json
    - run :  npx nyc merge coverage-reports && mv coverage.json .nyc_output/out.json
    - run :  npx nyc report --reporter lcov --report-dir coverage
    - run :  cat ./coverage/lcov.info | codacy-coverage --token ${{ secrets.CODACY_PROJECT_TOKEN }}
    - run :  bash <(curl -s https://codecov.io/bash)

    - name: Deploy with gh-pages
      if: github.ref == 'refs/heads/develop'
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -b website -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}